### ISSUE TITLE
おすし

### ISSUE THREAD

**Issue by matsui-a** [gouten5010/try-github#12]
# おすし

たべたい。

* まぐろ
* たまご
* いくら

![寿司ゆき:yes](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/01.png)

**Comment by 96usakoi** [comment]
# 文字おすし
* list

**Comment by hinaloe** [comment]
おすしですし？:sushi:

**Comment by gouten5010** [comment]
クローズですしおすし🍣
